### ISSUE TITLE
Web Interface 404

### ISSUE THREAD

**Issue by RumbleFrog** [nim4/DBShield#4]
## DBShield -c dbshield.yml

``404 page not found``

### My Config

```yml
##############################
### General               ###
#############################

# Operating mode
# possible values:
#       learning - add queries to training set (default)
#       protect - take action against abnormal queries
mode: learning

# DBMS type(default: mysql)
dbms: mariadb

# IP address to listen on(default: 0.0.0.0)
listenIP: 0.0.0.0

# Port number to listen on (0 means dbms default port ex. 3306 for mysql)
listenPort: 5000

# IP address of the server
targetIP: 127.0.0.1

# Port number of the dbms (0 means dbms default port ex. 3306 for mysql)
targetPort: 0

# TLS
tlsPrivateKey:  /etc/ssl/maxdb_key.pem
tlsCertificate: /etc/ssl/maxdb_certificate.pem

# Directory to save internal database(default: in model directory under OS's temp directory)
dbDir: "/tmp/model/"

# Connection timeout
# Valid units are "ns", "us" (or "µs"), "ms", "s", "m" and "h". (default: 5s)
timeout: 5s

# Databasse synchronisation interval, 0 will force sync after each commit.
# Valid units are "ns", "us" (or "µs"), "ms", "s", "m" and "h". (default: 5s)
SyncInterval: 5s

#############################
### HTTP Service          ###
#############################
# Run http interface(default: yes)
http: yes

# Serve https (default: yes)
httpSSL: no

# IP address to listen on(default: 127.0.0.1)
httpIP: 127.0.0.1

# Port number to listen on(default: 8070)
httpPort: 8070

# Password
httpPassword: ChangeMe

#############################
### Protect               ###
#############################

# Action to take against abnormal requests
# possible values:
#       drop  - close the connection (default)
#       pass  - pass the query to server
action: drop

# Properties to check for abnormality
#
# possible values: (you can choose more than one - comma separated)
#       user     - username
#       source   - request sourece address
#
# Note: leave empty to avoid adiditional checks
additionalChecks:  user,source

#############################
### Logging               ###
#############################

# Log depth
#       1   warning
#       2   info
#       4   debug
# default: 3 (warning + info)
logLevel: 3

# Log path
# possible values:
#       /path/to/file
#       stdout
#       stderr (default)
logPath: stderr
```

Was expecting something similar to the screenshot.

**DBShield Version**: ``1.0.0-beta4``
**Go Version**: ``go1.6.2 linux/amd64``
**OS Version**: ``Ubuntu 16.04.2 LTS Xenial``
